### ISSUE TITLE
ZoomEye - If added togheter with other engines, sometimes fail with the same error

### ISSUE THREAD

**Issue by AeonDave** [projectdiscovery/uncover#219] opened 2023-05-18 10:51 UTC
When performing multiple searches using the -e zoomeye command along with other search engines, an error occasionally occurs with the following panic message:

```
panic: interface conversion: interface {} is string, not float64
goroutine 58 [running]:
github.com/projectdiscovery/uncover/uncover/agent/zoomeye.(*Agent).query(0x0?, {0x1286f8b?, 0x0?}, 0x0?, 0x0?, 0x0?)
	/home/runner/work/uncover/uncover/uncover/agent/zoomeye/zoomeye.go:94 +0x4e5
github.com/projectdiscovery/uncover/uncover/agent/zoomeye.(*Agent).Query.func1()
	/home/runner/work/uncover/uncover/uncover/agent/zoomeye/zoomeye.go:42 +0x10b
created by github.com/projectdiscovery/uncover/uncover/agent/zoomeye.(*Agent).Query
	/home/runner/work/uncover/uncover/uncover/agent/zoomeye/zoomeye.go:31 +0xcc
```

### uncover version:
1.0.3

### Steps To Reproduce:
-r -silent -e shodan,censys,zoomeye -q "apache"

Note that this issue occurs intermittently, not consistently with every search.

**Comment by bongobongoland** [comment] 2023-05-20 23:52
have you tried 1.0.4?

**Comment by Paradigm00** [comment] 2023-05-22 08:23
with 1.0.4 -r and -j are broken so i cannot replicate the same behaviour.
response with -r -silent -e shodan,zoomeye -q "apache" is a blank line

**Comment by dogancanbakir** [comment] 2023-05-31 09:09
@AeonDave @Paradigm00 Fortunately, I could reproduce the issue, and I'm hopeful that the [PR (https://github.com/projectdiscovery/uncover/pull/228) will resolve it.

**Comment by dogancanbakir** [comment] 2023-05-31 09:17
@notwhy 
>uncover -shodan "ssl:aaa.com" -zoomeye "ssl:aaa.com +ssl.cert.availability:1"
it will ignore the +ssl.cert.availability:1 options and will found more garbage data.

It looks like you're using the [Multiple query against multiple search engine](https://github.com/projectdiscovery/uncover#multiple-query-against-multiple-search-engine) feature, which can run multiple queries against various providers. In your example, it's searching for the queries "ssl:aaa.com" and "ssl:aaa.com +ssl.cert.availability:1" on both shodan and zoomeye.

**Comment by ehsandeep** [comment] 2023-05-31 20:42
Fixed in latest release - https://github.com/projectdiscovery/uncover/releases/tag/v1.0.5

**Closed by ehsandeep** 2023-05-31 20:42 UTC
Labels: Status: Completed, Type: Bug
