### ISSUE TITLE
HunterHow - invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by bongobongoland** [projectdiscovery/uncover#185] opened 2023-03-29 03:29 UTC
I'm getting the following when trying to run hunterhow:

```console
$/home/kali/go/bin/uncover -q hunterhow.query -e hunterhow -l 1000 -o hunterhow.txt

[INF] Current uncover version v1.0.3 (latest)
[hunterhow] couldn't create new session: no default rate limit found for engine hunterhow
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc9cbd8]

goroutine 36 [running]:
github.com/projectdiscovery/uncover/uncover/agent/hunterhow.(*Agent).Query(0xc0004b5350?, 0xe3f9d9?, 0xdd7d93?)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/uncover@v1.0.3/uncover/agent/hunterhow/hunterhow.go:24 +0x18
github.com/projectdiscovery/uncover/runner.(*Runner).Run.func1({0x1031a70, 0x162eaf0}, 0xc00040e450?)
        /home/kali/go/pkg/mod/github.com/projectdiscovery/uncover@v1.0.3/runner/runner.go:184 +0x4af
created by github.com/projectdiscovery/uncover/runner.(*Runner).Run
        /home/kali/go/pkg/mod/github.com/projectdiscovery/uncover@v1.0.3/runner/runner.go:165 +0x1cdb
```

Am I missing something? Do I need to edit something?
Also, there's no HunterHow's key section in the provider-config.yaml file.

**Comment by Mzack9999** [comment] 2023-05-07 14:31
@bongobongoland I am unable to reproduce this issue as it probably got indirectly fixed as part of https://github.com/projectdiscovery/uncover/pull/201

```console
$ uncover -q hunterhow.query -e hunterhow -l 1000 -o hunterhow.txt

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/

                projectdiscovery.io

[INF] Current uncover version v1.0.4-dev (dev)
[FTL] Could not run enumeration: [uncover:RUNTIME] agents [hunterhow] requires keys, but no keys were found

exit status 1
```

Could you check if you can still reproduce it with the latest version?
Thanks!

**Comment by bongobongoland** [comment] 2023-05-10 08:56
ok, getting a different output now.


[INF] Current uncover version v1.0.4 (latest)
[hunterhow] the optional range of page size is 10 20 50 100

**Comment by bongobongoland** [comment] 2023-05-10 23:36
so what do I do? :) please advise

**Comment by Mzack9999** [comment] 2023-05-11 00:13
Did you configure a key in `provider-config.yaml`? I'm getting this output with the command you provided
```console
$ uncover -q hunterhow.query -e hunterhow -l 1000 -o hunterhow.txt

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /    
\__,_/_/ /_/\___/\____/|___/\___/_/

                projectdiscovery.io

[INF] Current uncover version v1.0.4 (latest)
[FTL] Could not run enumeration: [uncover:RUNTIME] agents [hunterhow] requires keys but no keys were found
exit status 1
```

**Comment by bongobongoland** [comment] 2023-05-11 04:43
yeah, I have a key.

**Comment by bongobongoland** [comment] 2023-05-11 04:47
If I'm not mistaken, 

`[hunterhow] the optional range of page size is 10 20 50 100`

is a response from hunterhow

**Comment by Mzack9999** [comment] 2023-05-18 04:50
@bongobongoland I'm not able to reproduce the issue. We can better investigate if you provide all the steps, queries, and configurations you use. For the record, I'm doing this:

```console
$ cat providers.yaml
shodan: []
censys: []
fofa: []
quake:
hunter: []
zoomeye: []
netlas: []
criminalip: []
publicwww: []
hunterhow:
  - "xxx" # valid key
$ cat hunterhow.query
test
$ uncover -q hunterhow.query -e hunterhow -l 1000 -o hunterhow.txt -pc providers.yaml

  __  ______  _________ _   _____  _____
 / / / / __ \/ ___/ __ \ | / / _ \/ ___/
/ /_/ / / / / /__/ /_/ / |/ /  __/ /
\__,_/_/ /_/\___/\____/|___/\___/_/

                projectdiscovery.io

[INF] Current uncover version v1.0.4 (latest)
```

**Comment by bongobongoland** [comment] 2023-05-22 06:41
put anything other than test in your query file.
                                                             
try
           
ip.port=="666" and ip.country=="US"

**Comment by ehsandeep** [comment] 2023-05-31 20:42
Fixed in latest release - https://github.com/projectdiscovery/uncover/releases/tag/v1.0.5

**Closed by ehsandeep** 2023-05-31 20:42 UTC
Labels: Status: Completed, Type: Bug
