### ISSUE TITLE
Search queries with commas (`,`) get splitted into multiple queries when using Shodan

### ISSUE THREAD

**Issue by jimen0** [projectdiscovery/uncover#27] opened 2022-04-06 12:14 UTC
### uncover version

projectdiscovery/uncover@be23df81db2678f9e32e13faf57463ae729d3ddf compiled using `go version devel go1.19-5bb2628c6f  darwin/amd64`

### Current Behavior

```console
$ cat $HOME/.config/uncover/config.yaml 
query:
  - 'org:"Something, Inc."' 

engine: shodan
...
```

Results in the following queries issues by the tool:

```console
[shodan] unexpected status code 502 received from https://api.shodan.io/shodan/host/search?key=REDACTED&query=org:"Something&page=1
[shodan] unexpected status code 502 received from https://api.shodan.io/shodan/host/search?key=REDACTED&query= Inc."&page=1
```

### Expected Behavior

A single query is issued using my raw string, urlencoding it if needed.

### Steps To Reproduce:

```console
$ SHODAN_API_KEY=REPLACE-WITH-YOURS uncover -q 'org:"Something, Inc."' -v
```

### Anything else

For now I've fixed this by doing the needed changes in order for the program to handle Query parameter as a string type rather than `goflags.FileCommaSeparatedStringSlice`. Please, note this required more changes but I avoided pasting them there.

```diff
diff --git a/runner/options.go b/runner/options.go
index 17804d6..a23b7e5 100644
--- a/runner/options.go
+++ b/runner/options.go
@@ -23,7 +23,7 @@ var (
 
 // Options contains the configuration options for tuning the enumeration process.
 type Options struct {
-       Query        goflags.FileCommaSeparatedStringSlice
+       Query        string
```

Would be happy to contribute a change to use Query as a `string`, but maybe the proper fix is to make `goflags.FileCommaSeparatedStringSlice` properly handle quotted commas? I'll leave that decision to your team! 😃

**Comment by ehsandeep** [comment] 2022-04-13 17:05
@jimen0, thanks again for reporting this. This is now fixed in the [latest release](https://github.com/projectdiscovery/uncover/releases/tag/v0.0.5).

**Comment by ehsandeep** [comment] 2022-11-09 14:44
looks like we have regression of this bug, reopening for further tracking.

**Closed** 2022-11-29 19:16 UTC
Labels: Priority: High, Priority: Medium, Status: Completed, Type: Bug
